Update SQLUtils.java
alibaba/druid pull request #5059
Opened 2022-12-24 13:31 UTC by ShaneKing

select someColumn from "someSchema"."somePostgreSqlTable"

2023-02-27 14:36 UTC, kimmking commented
/ci

2023-02-27 14:41 UTC, kimmking commented on core/src/main/java/com/alibaba/druid/sql/SQLUtils.java
> +                    } else if (c0 == '"') {
hello, can you tell me why add two  escape characters here?

2023-03-05 03:57 UTC, ShaneKing commented on core/src/main/java/com/alibaba/druid/sql/SQLUtils.java
> +                    } else if (c0 == '"') {
because `select someColumn from "someSchema"."somePostgreSqlTable"` is support in postgresql.

2023-04-18 18:42 UTC, kimmking requested changes

2023-04-18 18:42 UTC, kimmking commented on core/src/main/java/com/alibaba/druid/sql/SQLUtils.java
> +                    } else if (c0 == '"') {
but I try it in mysql and cause error, so could we fix it and only affect pgsql datasource?

2023-12-14 16:34 UTC, closed without merging