fix: 修复SQL防火墙之SQL条件总真(WhereAlwayTrue)功能无效问题(条件写反了)
alibaba/druid pull request #5698
Opened 2024-01-20 05:15 UTC by qxo

包含这三项配置对应功能:deleteWhereAlwayTrue/updateWhereAlwayTrue/selectWhereAlwayTrue 并修正了PGWallVisitor/SQLServerWallVisitor

2024-01-21 01:50 UTC, zrlw commented
30个单元测试都失败，确定单元测试都写错了？

2024-01-21 04:12 UTC, qxo commented
> 30个单元测试都失败，确定单元测试都写错了？

此事我很是诧异, 好像从没正确过....
已经把测试用例和修复代码提交了, 此事请项目负责人接管核实吧

2024-01-21 04:51 UTC, qxo commented
> > 30个单元测试都失败，确定单元测试都写错了？
> 
> 此事我很是诧异, 好像从没正确过.... 已经把测试用例和修复代码提交了, 此事请项目负责人接管核实吧

应该是部分逻辑写反了, 而之前的测试用没覆盖到场景, 所以修正代码后所有测试用例也是正常的

2024-01-24 03:51 UTC, zrlw commented
2024-01-20T05:58:34.1417283Z [ERROR] Failures: 
2024-01-20T05:58:34.1417981Z [ERROR]   TenantSelectTest4.testMySql:53 expected:<0> but was:<1>
2024-01-20T05:58:34.1418798Z [ERROR]   TenantSelectTest4.testMySql2:62 expected:<0> but was:<1>
2024-01-20T05:58:34.1419497Z [ERROR]   WallDeleteWhereTest.testMySql:32
2024-01-20T05:58:34.1420185Z [ERROR]   WallDeleteWhereTest.testORACLE:37
2024-01-20T05:58:34.1420933Z [ERROR]   WallDeleteWhereTest2.test_check_true:38
2024-01-20T05:58:34.1421624Z [ERROR]   WallSelectWhereTest.testMySql:33
2024-01-20T05:58:34.1422146Z [ERROR]   WallSelectWhereTest.testORACLE:37
2024-01-20T05:58:34.1422561Z [ERROR]   WallSelectWhereTest6.test_check_true:39
2024-01-20T05:58:34.1422954Z [ERROR]   WallUnionTest.testMySql:34
2024-01-20T05:58:34.1423292Z [ERROR]   WallUnionTest.testOracle:41
2024-01-20T05:58:34.1423634Z [ERROR]   WallUnionTest2.testMySql:34
2024-01-20T05:58:34.1424192Z [ERROR]   WallUnionTest2.testOracle:43
2024-01-20T05:58:34.1424644Z [ERROR]   WallUnionTest4.testMySql:34
2024-01-20T05:58:34.1424995Z [ERROR]   WallUnionTest4.testORACLE:43
2024-01-20T05:58:34.1425343Z [ERROR]   WallUpdateTest3.testMySql:41
2024-01-20T05:58:34.1425687Z [ERROR]   WallUpdateTest3.testORACLE:46
2024-01-20T05:58:34.1426063Z [ERROR]   WallUpdateWhereTest.testMySql:34
2024-01-20T05:58:34.1426457Z [ERROR]   WallUpdateWhereTest.testORACLE:39
2024-01-20T05:58:34.1426867Z [ERROR]   WallUpdateWhereTest1.test_check_true:38
2024-01-20T05:58:34.1427243Z [ERROR]   MySqlWallTest63.test_true:40
2024-01-20T05:58:34.1427675Z [ERROR]   MySqlWallTest74.test_false:38
2024-01-20T05:58:34.1428021Z [ERROR]   MySqlWallTest90.test_true:38
2024-01-20T05:58:34.1428347Z [ERROR]   MySqlWallTest91.test:245
2024-01-20T05:58:34.1428770Z [ERROR]   MySqlWallTest91.test_false3:78
2024-01-20T05:58:34.1429119Z [ERROR]   MySqlWallTest91.test_false4:86
2024-01-20T05:58:34.1429470Z [ERROR]   MySqlWallTest91.test_false5:94
2024-01-20T05:58:34.1429823Z [ERROR]   MySqlWallTest91.test_false6:102
2024-01-20T05:58:34.1430193Z [ERROR]   MySqlWallTest_union.testUnion:30
2024-01-20T05:58:34.1430557Z [ERROR]   OracleWallTest.testWall:29
2024-01-20T05:58:34.1430928Z [ERROR]   AntlrMySqlTest.test_for_antlr_examples:39

修订的单元测试没有提交？还是30个错误

2024-01-24 16:09 UTC, qxo commented
github 都构建成功了, 应该提交了, 今天github无法访问, 没法确认



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rossen ***@***.***&gt;; 
发送时间: 2024年1月24日(星期三) 中午11:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/druid] fix: 修复SQL防火墙之SQL条件总真(WhereAlwayTrue)功能无效问题(条件写反了) (PR #5698)





 
2024-01-20T05:58:34.1417283Z [ERROR] Failures:
 2024-01-20T05:58:34.1417981Z [ERROR]   TenantSelectTest4.testMySql:53 expected:<0&gt; but was:<1&gt;
 2024-01-20T05:58:34.1418798Z [ERROR]   TenantSelectTest4.testMySql2:62 expected:<0&gt; but was:<1&gt;
 2024-01-20T05:58:34.1419497Z [ERROR]   WallDeleteWhereTest.testMySql:32
 2024-01-20T05:58:34.1420185Z [ERROR]   WallDeleteWhereTest.testORACLE:37
 2024-01-20T05:58:34.1420933Z [ERROR]   WallDeleteWhereTest2.test_check_true:38
 2024-01-20T05:58:34.1421624Z [ERROR]   WallSelectWhereTest.testMySql:33
 2024-01-20T05:58:34.1422146Z [ERROR]   WallSelectWhereTest.testORACLE:37
 2024-01-20T05:58:34.1422561Z [ERROR]   WallSelectWhereTest6.test_check_true:39
 2024-01-20T05:58:34.1422954Z [ERROR]   WallUnionTest.testMySql:34
 2024-01-20T05:58:34.1423292Z [ERROR]   WallUnionTest.testOracle:41
 2024-01-20T05:58:34.1423634Z [ERROR]   WallUnionTest2.testMySql:34
 2024-01-20T05:58:34.1424192Z [ERROR]   WallUnionTest2.testOracle:43
 2024-01-20T05:58:34.1424644Z [ERROR]   WallUnionTest4.testMySql:34
 2024-01-20T05:58:34.1424995Z [ERROR]   WallUnionTest4.testORACLE:43
 2024-01-20T05:58:34.1425343Z [ERROR]   WallUpdateTest3.testMySql:41
 2024-01-20T05:58:34.1425687Z [ERROR]   WallUpdateTest3.testORACLE:46
 2024-01-20T05:58:34.1426063Z [ERROR]   WallUpdateWhereTest.testMySql:34
 2024-01-20T05:58:34.1426457Z [ERROR]   WallUpdateWhereTest.testORACLE:39
 2024-01-20T05:58:34.1426867Z [ERROR]   WallUpdateWhereTest1.test_check_true:38
 2024-01-20T05:58:34.1427243Z [ERROR]   MySqlWallTest63.test_true:40
 2024-01-20T05:58:34.1427675Z [ERROR]   MySqlWallTest74.test_false:38
 2024-01-20T05:58:34.1428021Z [ERROR]   MySqlWallTest90.test_true:38
 2024-01-20T05:58:34.1428347Z [ERROR]   MySqlWallTest91.test:245
 2024-01-20T05:58:34.1428770Z [ERROR]   MySqlWallTest91.test_false3:78
 2024-01-20T05:58:34.1429119Z [ERROR]   MySqlWallTest91.test_false4:86
 2024-01-20T05:58:34.1429470Z [ERROR]   MySqlWallTest91.test_false5:94
 2024-01-20T05:58:34.1429823Z [ERROR]   MySqlWallTest91.test_false6:102
 2024-01-20T05:58:34.1430193Z [ERROR]   MySqlWallTest_union.testUnion:30
 2024-01-20T05:58:34.1430557Z [ERROR]   OracleWallTest.testWall:29
 2024-01-20T05:58:34.1430928Z [ERROR]   AntlrMySqlTest.test_for_antlr_examples:39
 
修订的单元测试没有提交？还是30个错误
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-01-25 05:04 UTC, zrlw commented
github显示你最后一次提交的是：
[qxo](https://github.com/qxo) [force-pushed](https://github.com/alibaba/druid/compare/9d624b4a510bb4fb1c136af2c9bde48b5d1375be..6393f022c4b4ec64a586d4da5408bd707aed778c) the fix-wall-deleteWhereAlwaysTrue branch from [9d624b4 ](https://github.com/alibaba/druid/commit/9d624b4a510bb4fb1c136af2c9bde48b5d1375be)to [6393f02 ](https://github.com/alibaba/druid/commit/6393f022c4b4ec64a586d4da5408bd707aed778c)
[5 days ago](https://github.com/alibaba/druid/pull/5698#event-11544986701)

github构建失败：
@github-actions
Java CI / Test JDK 17, ubuntu-latest (pull_request) Failing after 3m
点开查看detail有30个单元测试失败

github通常要fan才能正常访问。

2024-01-25 05:10 UTC, zrlw commented
github页面显示只修改了5个文件，应该是你单元测试相关修订的push操作失败了，可以查看一下你本地的git log，应该和github显示的最后一个提交 [9d624b4 ](https://github.com/alibaba/druid/commit/9d624b4a510bb4fb1c136af2c9bde48b5d1375be) 不同。

2024-01-25 14:34 UTC, qxo commented
> github页面显示只修改了5个文件，应该是你单元测试相关修订的push操作失败了，可以查看一下你本地的git log，应该和github显示的最后一个提交 [9d624b4 ](https://github.com/alibaba/druid/commit/9d624b4a510bb4fb1c136af2c9bde48b5d1375be) 不同。

我这显示和上游是一致的, 是5文件没错,但commitId为:6393f022c
为什么JDK17下我抽时间排查一下吧

2024-01-25 14:53 UTC, qxo commented
我们先重新理此问题定义,&nbsp;WhereAlwayTrue=true时这个SQL算正常不: `where 1=1 limit 1,10`





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rossen ***@***.***&gt;; 
发送时间: 2024年1月25日(星期四) 中午1:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/druid] fix: 修复SQL防火墙之SQL条件总真(WhereAlwayTrue)功能无效问题(条件写反了) (PR #5698)





 
github页面显示只修改了5个文件，应该是你单元测试相关修订的push操作失败了，可以查看一下你本地的git log，应该和github显示的最后一个提交 9d624b4  不同。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-01-26 02:26 UTC, zrlw commented
为了兼顾druid-spring-boot-3-starter，druid的github构建脚本只配了jdk17执行单元测试，jdk8环境下只编译代码，并不执行单元测试案例。

2024-01-26 02:36 UTC, zrlw commented
当selectWhereAlwayTrueCheck、deleteWhereAlwayTrueCheck、updateWhereAlayTrueCheck（这个属性名称丢了一个w字母，最好加上）为true：检查相关where条件是否恒为真，此时相关where 1=1应该视为错误。
如果上述check选项为false，则不检查where条件，此时where 1=1应该视为正常。

2024-01-26 02:46 UTC, zrlw commented
如果是[6393f02](https://github.com/alibaba/druid/commit/6393f022c4b4ec64a586d4da5408bd707aed778c)，那你本地跑mvn test也会有30个单元测试错误。

2024-01-26 02:48 UTC, zrlw commented
这个PR需要修改的单元测试类都不只5个。

2024-01-26 03:12 UTC, zrlw requested changes

2024-01-26 03:12 UTC, zrlw commented on core/src/main/java/com/alibaba/druid/wall/WallProvider.java
> +            endOfComment = lastToken == Token.EOF || parser.getLexer().isEndOfComment();
建议和其他endOfComment的判定条件保持一致：
```
endOfComment = parser.getLexer().isEOF(); 
```

2024-01-26 03:21 UTC, zrlw requested changes

2024-01-26 03:21 UTC, zrlw commented on core/src/main/java/com/alibaba/druid/wall/spi/WallVisitorUtils.java
>                  if (visitor.getConfig().isSelectWhereAlwayTrueCheck()
visitor.getConfig().isSelectWhereAlwayTrueCheck() 前面getConditionValue也有作为入参，但并没有用到，建议这个PR同时把getConditionValue方法也一起改了，用不到的入参直接删掉吧。

2024-01-26 03:22 UTC, zrlw commented
还有这个updateWhereAlayTrueCheck丢了字母的变量名，最好也一起改了

2024-01-26 14:18 UTC, qxo commented
> 还有这个updateWhereAlayTrueCheck丢了字母的变量名，最好也一起改了
这是另一个问题,其实我们内部分支已做兼容性修正, 外部的话得看是否有业余时间另外提交对应PR

2024-01-26 14:20 UTC, qxo commented on core/src/main/java/com/alibaba/druid/wall/WallProvider.java
> +            endOfComment = lastToken == Token.EOF || parser.getLexer().isEndOfComment();
此处不调整我还不清楚如何兼容修改正问题, 有空时我再看看

2024-01-26 14:36 UTC, qxo commented
> 当selectWhereAlwayTrueCheck、deleteWhereAlwayTrueCheck、updateWhereAlayTrueCheck（这个属性名称丢了一个w字母，最好加上）为true：检查相关where条件是否恒为真，此时相关where 1=1应该视为错误。 如果上述check选项为false，则不检查where条件，此时where 1=1应该视为正常。

如果这样的相关测试用例也写反了... 昨我还一度以为之前我对定义理解错了...以为: `where 1=1` 应该等同于没有where的场景

2024-01-27 05:08 UTC, zrlw commented on core/src/main/java/com/alibaba/druid/wall/WallProvider.java
> +            endOfComment = lastToken == Token.EOF || parser.getLexer().isEndOfComment();
> 此处不调整我还不清楚如何兼容修改正问题, 有空时我再看看

druid其他代码都是用parser.getLexer().isEOF()方法设置endOfComment标识，此处写作parser.getLexer().isEndOfComment()应该是笔误。

2024-01-27 05:10 UTC, zrlw commented
> > 当selectWhereAlwayTrueCheck、deleteWhereAlwayTrueCheck、updateWhereAlayTrueCheck（这个属性名称丢了一个w字母，最好加上）为true：检查相关where条件是否恒为真，此时相关where 1=1应该视为错误。 如果上述check选项为false，则不检查where条件，此时where 1=1应该视为正常。
> 
> 如果这样的相关测试用例也写反了... 昨我还一度以为之前我对定义理解错了...以为: `where 1=1` 应该等同于没有where的场景

不知道从什么版本开始这个检查功能就是个摆设了，侧面也说明这个功能很少有人用。

2024-01-28 00:12 UTC, zrlw commented
[fix: 修正测试用户逻辑](https://github.com/alibaba/druid/pull/5698/commits/84707ed2936d1a2715b28275fe3f009acd9059a1)这个commit有20个测试ERROR：
2024-01-27T16:08:50.6612964Z [ERROR]   WallUnionTest2.testMySql:34
2024-01-27T16:08:50.6613602Z [ERROR]   WallUnionTest2.testOracle:43
2024-01-27T16:08:50.6614202Z [ERROR]   WallUnionTest4.testMySql:34
2024-01-27T16:08:50.6616489Z [ERROR]   WallUnionTest4.testORACLE:43
2024-01-27T16:08:50.6617366Z [ERROR]   WallUpdateTest3.testMySql:41
2024-01-27T16:08:50.6617998Z [ERROR]   WallUpdateTest3.testORACLE:46
2024-01-27T16:08:50.6618641Z [ERROR]   WallUpdateWhereTest.testMySql:34
2024-01-27T16:08:50.6619301Z [ERROR]   WallUpdateWhereTest.testORACLE:39
2024-01-27T16:08:50.6619990Z [ERROR]   WallUpdateWhereTest1.test_check_true:38
2024-01-27T16:08:50.6620651Z [ERROR]   MySqlWallTest63.test_true:40
2024-01-27T16:08:50.6621231Z [ERROR]   MySqlWallTest74.test_false:38
2024-01-27T16:08:50.6621816Z [ERROR]   MySqlWallTest90.test_true:38
2024-01-27T16:08:50.6622404Z [ERROR]   MySqlWallTest91.test:245
2024-01-27T16:08:50.6622762Z [ERROR]   MySqlWallTest91.test_false3:78
2024-01-27T16:08:50.6623138Z [ERROR]   MySqlWallTest91.test_false4:86
2024-01-27T16:08:50.6623786Z [ERROR]   MySqlWallTest91.test_false5:94
2024-01-27T16:08:50.6624223Z [ERROR]   MySqlWallTest91.test_false6:102
2024-01-27T16:08:50.6624755Z [ERROR]   MySqlWallTest_union.testUnion:30
2024-01-27T16:08:50.6625139Z [ERROR]   OracleWallTest.testWall:29
2024-01-27T16:08:50.6625534Z [ERROR]   AntlrMySqlTest.test_for_antlr_examples:39

2024-01-28 00:22 UTC, qxo commented
看到了, 还没修改完呢, 因昨codespace网络有问题切换回本地所以临时先提交了

越修改测试用例越有疑问: 如果只是写反了, 怎么可能这么我测试代码其逻辑也是反的....




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rossen ***@***.***&gt;; 
发送时间: 2024年1月28日(星期天) 上午8:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/druid] fix: 修复SQL防火墙之SQL条件总真(WhereAlwayTrue)功能无效问题(条件写反了) (PR #5698)





 
fix: 修正测试用户逻辑这个commit有20个测试ERROR：
 2024-01-27T16:08:50.6612964Z [ERROR]   WallUnionTest2.testMySql:34
 2024-01-27T16:08:50.6613602Z [ERROR]   WallUnionTest2.testOracle:43
 2024-01-27T16:08:50.6614202Z [ERROR]   WallUnionTest4.testMySql:34
 2024-01-27T16:08:50.6616489Z [ERROR]   WallUnionTest4.testORACLE:43
 2024-01-27T16:08:50.6617366Z [ERROR]   WallUpdateTest3.testMySql:41
 2024-01-27T16:08:50.6617998Z [ERROR]   WallUpdateTest3.testORACLE:46
 2024-01-27T16:08:50.6618641Z [ERROR]   WallUpdateWhereTest.testMySql:34
 2024-01-27T16:08:50.6619301Z [ERROR]   WallUpdateWhereTest.testORACLE:39
 2024-01-27T16:08:50.6619990Z [ERROR]   WallUpdateWhereTest1.test_check_true:38
 2024-01-27T16:08:50.6620651Z [ERROR]   MySqlWallTest63.test_true:40
 2024-01-27T16:08:50.6621231Z [ERROR]   MySqlWallTest74.test_false:38
 2024-01-27T16:08:50.6621816Z [ERROR]   MySqlWallTest90.test_true:38
 2024-01-27T16:08:50.6622404Z [ERROR]   MySqlWallTest91.test:245
 2024-01-27T16:08:50.6622762Z [ERROR]   MySqlWallTest91.test_false3:78
 2024-01-27T16:08:50.6623138Z [ERROR]   MySqlWallTest91.test_false4:86
 2024-01-27T16:08:50.6623786Z [ERROR]   MySqlWallTest91.test_false5:94
 2024-01-27T16:08:50.6624223Z [ERROR]   MySqlWallTest91.test_false6:102
 2024-01-27T16:08:50.6624755Z [ERROR]   MySqlWallTest_union.testUnion:30
 2024-01-27T16:08:50.6625139Z [ERROR]   OracleWallTest.testWall:29
 2024-01-27T16:08:50.6625534Z [ERROR]   AntlrMySqlTest.test_for_antlr_examples:39
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-01-28 23:00 UTC, zrlw commented
我也不知道为什么会有这么多错误的单元测试，可能这些单元测试案例都是恒真条件检查机制失效后加的。

2024-01-28 23:01 UTC, zrlw commented
或许这些错误的单元测试需要将恒真检查选项设为false。

2024-02-19 16:11 UTC, merged

2024-06-24 10:37 UTC, CantosSong commented
wall的默认行为，如果从false变成true 会对用到的人有影响，更应该默认是false

2024-06-24 10:38 UTC, CantosSong commented
> wall的默认行为，如果从false变成true 会对用到的人有影响，更应该默认是false

当然，updateWhereAlwayTrueCheck 定义没问题，但是原始的默认值是false,修改为true就会对既有项目有影响